import { Roboto_Mono } from "next/font/google";
import NavBar from "./components/navbar/NavBar";
import "./globals.css";


const roboto_mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Github user finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={roboto_mono.className}>
        <div className="grid min-h-screen place-content-center bg-blue-50 px-4 dark:bg-blue-950 ">
          <div className="sm:w-[500px] md:w-[600px] lg:w-[700px]">
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
